manifest = "d6eb3bb5dd9b9856aac54e5f0e782f2b7887b3a2d11a860722d9fcfea5d7a4f2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.30.1" ]
revision = "d3841f943720f92cd83ee7cadfc1ab7342e23056"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.1" ]
revision = "211cb1839d5488e44299309a5af011b0a9dff8d3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.30.1" ]
revision = "5ffdf499e338c885abf953360a334b3d3ba71c96"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.30.1" ]
revision = "bdb239118b51573117acd20029742fee6e7551f3"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.30.1" ]
revision = "504cc3cb91028452b397806c6c9bce4c2cee3a78"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.30.1" ]
revision = "a88739e04cc0f241c094e641574672f00c61bc40"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.30.1" ]
revision = "a31a71bb5ec767d069628c8d6f26c4a908b9d8d2"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.30.1" ]
revision = "3ea501bb38665e52dfde7ff3a172be2b7b51fcea"
