manifest = "4f60b587d735f4cffabaffa5083d5a246e8d36a05054f43f3713ef6f9b6fcf65"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.33.1" ]
revision = "34111202245f4c5896eb303c23d4cdc4bf590627"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.1" ]
revision = "fc0cda2c8601a5e6f1371a7d8f5f6152c73d8ad6"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.1" ]
revision = "163dee0104360b973f2b5b5dd4f786b991418a90"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.33.1" ]
revision = "d960d4cc76752d05685e8bee42ad289c1ef92330"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.33.1" ]
revision = "7a19606a1ccef0702ac61ba19d5e4bbe759c8949"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.33.1" ]
revision = "af7fe0371043059d6c425a7f06d75e1c367e5559"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.1" ]
revision = "ec60ccce30c2d3b0a362500e37817d249aa1114e"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.33.1" ]
revision = "4d4141c4a8d814be8d17deae5fb6eb18b71b29a6"
