manifest = "7c0fdba0174c0b749be8e390347c259ccdaff51a0a7922a112509cc2bdda6566"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type-index"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.62.0" ]
revision = "484f0f9359c0896a0ea9ae1f471c4586b2bb1591"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.62.0" ]
revision = "8b7c48e29eba8eaf4f1f8d1641099762c6e5bdda"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.62.0" ]
revision = "8e0bd7d950d98d4dd62a61b31ad6cd90e0ab3fd9"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.62.0" ]
revision = "68bae388b72838706adf21b00e556ab0d3757682"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.62.0" ]
revision = "aabf1b51ad20471ec869ae8db30d4f8da170e6a2"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.62.0" ]
revision = "61e5cbe0edab2492008d5e8a7966ac70aada9dfa"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.62.0" ]
revision = "1b516c700dd073c8a500fdfd016dc35c1713fdb8"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.62.0" ]
revision = "9378469b54345a1ac6c6ae67a50cff8e56c3e993"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.62.0" ]
revision = "aed0a64c4a565f629c3ae67e1ab0657ff6934db7"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.62.0" ]
revision = "92612185e7bae70d2e2a614509f031c535331c14"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.62.0" ]
revision = "2cdcf5ef16c96a2f934b2331c01c1e23cb46ce9f"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.62.0" ]
revision = "0df92728113f7c2f1125f2996c4531e93162a222"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.62.0" ]
revision = "23e63d9e05df6b6833894d34b2fcaf72c15b9cfc"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.62.0" ]
revision = "3ddcf9ceb2f5b7894128928e2bc8bb03ddca16b7"
