manifest = "4489df53815f78ab39a9fe7ad74841c94f67a66b4484e970d87fe8219c557fd0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type-index"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.67.0" ]
revision = "d33f5202a6d3d8e42cccd641c8d78e7b467fec8d"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.67.0" ]
revision = "39c0cb87cdd469dfc4e2b11a0a3808efaa06d0a3"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.67.0" ]
revision = "5782f108397199eccd4404780d37513b42798a43"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.67.0" ]
revision = "84228d56959e4c51ccf06a357f0fac7b7a3310c9"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.67.0" ]
revision = "205cacd6bff72f09635287926d379c56ec87899d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.67.0" ]
revision = "feb7fef2d9afa1f1e2f33d4a6a2d9d63aadd1d24"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.67.0" ]
revision = "af60423789ba4451f4f4fb4749ffaabc6a764a3c"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.67.0" ]
revision = "abb6723e92f251a4ca7987798221ef215cea1137"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.67.0" ]
revision = "aa51a0a1e2936c78fa448bdada5a0ca6754f0b54"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.67.0" ]
revision = "22306e2d01a69ad400e7c1963699e2139edb4d10"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.67.0" ]
revision = "a74c9272293ae55fc1e65e10c791979862db8368"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.67.0" ]
revision = "7ffe0f3ebd7dae27f92216fb3e017e77e3d41481"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.67.0" ]
revision = "7554865aad1e357c2ce1300060e87f1f44f9d3b0"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.67.0" ]
revision = "e747dc0d16ea6393f4e6383581a884974b07796d"
