manifest = "67343a24e1c7420d5e66f23968a9b77ebd0b5df778fe3e912db8a15b70a022f7"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type-index"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.66.0" ]
revision = "8dc91ee53734be8ff8ce63685788490d0ad30b6d"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.66.0" ]
revision = "0bda91490edebf069f2e20d7cd98b3333e28b924"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.66.0" ]
revision = "bbc1bc3ec06d91bea9ee8e8e9b900de37998e063"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.66.0" ]
revision = "d4f5c96f96cce678c705cbd362dabc364a81a4c9"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.66.0" ]
revision = "a7be6c827538ef90c7dba6e10cf00dc14584b75d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.66.0" ]
revision = "06136d7b02f567829df8d287d7bc95158a346f21"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.66.0" ]
revision = "9ef0ad8898e51321477a55e9ec7886db33ae50f3"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.66.0" ]
revision = "9425eb4e908dfb6ecb96db9beaee44a71574ff43"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.66.0" ]
revision = "f40e33d9d3096ea6cf213b206be9f8c5ff0fe1ac"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.66.0" ]
revision = "e1dc6ac4af7aeeb5ddb3c9d979531137e0f30816"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.66.0" ]
revision = "d08737c5cc1a99ba23cd062cbd04ed53eda32377"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.66.0" ]
revision = "dcddb73ec829885e89811914e847fb1d7e3c40f3"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.66.0" ]
revision = "5cd1a1d9158e4ce809ec637947e2d8ad4ca115b9"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.66.0" ]
revision = "13a62020ec56b6e2d11c9ff79a69d38f4d38fd74"
