manifest = "12f7548cfab59e108feb4af706b41bb1b21b1a6e3da99ae7ea67764490788d53"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.30.0" ]
revision = "b9f50744ef3e53844221598731ec8dd593a3b35a"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.0" ]
revision = "95f590da8eb5534e7a02b750ef5a5487e8f5a799"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.30.0" ]
revision = "83b29b8b518ba5c6ffa205e7c484ac06b226d7d7"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.30.0" ]
revision = "d9db5c373fc5442e9659354737d5bf8a0d052e4c"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.30.0" ]
revision = "d436ad7088b14951350d6b941337f72ac343be43"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.30.0" ]
revision = "cb31d4d23e3d73c99054f7349f1cbc9a90e70367"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.30.0" ]
revision = "f99e6877ad72672942fefa948cb582ec069cabba"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.30.0" ]
revision = "42c5d2d94f348428fb9548aa31d30c67bd665a93"
