manifest = "66eeb2c6dbc5c261fa90b3eaf36fec6c2b5d4e5fd219c2023bbdc97e9d0c49ed"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
target = "//:type-index"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.56.0" ]
revision = "9d1a6e0a4a74ad3af0ade7285ab5edd52c6fd860"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.56.0" ]
revision = "be9837a4290e26be9d6470428142d0968a36e7bb"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.56.0" ]
revision = "edb8562f816250216903f89ec4d9ac0961a922a1"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.56.0" ]
revision = "a0b449aba11f1f0ce9afea3ec681b62438a91100"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.56.0" ]
revision = "599096bd0a9ca5ecd901886f09046e3f7ce05556"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.56.0" ]
revision = "baeb2fb09197e1422a40481e9080e17c75cd50cf"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.56.0" ]
revision = "6da7bf765b989720d67fee49d07f5d8e56663d5b"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.56.0" ]
revision = "68e4e54f50d15baa85f355a3ad9c3004126883f6"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.56.0" ]
revision = "ad21a117be237ab693f723782c5581bb58ce8875"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.56.0" ]
revision = "37f8e9a9f7a9e93ab1ebed5fc2f8614d3c52e710"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.56.0" ]
revision = "f7cd6c73ebbbd290cf37c64141e76f12dcfed467"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.56.0" ]
revision = "072bacba5243762657af3d7296f487082d3b41be"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.56.0" ]
revision = "9641085a42a25ca196d08d542862616f877cf693"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.56.0" ]
revision = "4cb87af8e2e77f0826f17eca369395ba86ef1a17"
