targets = ["//:function"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
version = "1.70.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.70.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
version = "1.70.0"
