manifest = "a97e438a2e75221a8b8c3ad044e74fd61178602a471e9a5dc7ee2cb207606d54"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.55.0" ]
revision = "6894aca9c2c2e8a5f192f85e2258cc17e1718b3c"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.55.0" ]
revision = "892598f066f15a4b8352bbd6b5f2b1a90e12e6fc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.55.0" ]
revision = "8fe65abe2334e0d84c2cba4c768ec2f2360b33e1"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.55.0" ]
revision = "6e1f8747229dfb5a62a5c55671f82b9c671db417"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.55.0" ]
revision = "a41bc5546421204bda9a1572a75474b7197559b2"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.55.0" ]
revision = "e14d6eb7ed4f944d0c0bb723e4732c5ea80d0d1d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.55.0" ]
revision = "e53e7e72e660990dcc5c6c015d724fab0c4516a6"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.55.0" ]
revision = "59b48f8ac824d7985183ffb3c3174c8caebfef20"
